# This is a basic workflow to help you get started with Actions

name: Build Package

# Controls when the workflow will run
on:
  # Triggers the workflow on push
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com/'
          scope: "@easy-games"

      # Runs a set of commands using the runners shell
      - name: Publish Package
        run: |
          npm --no-git-tag-version version $(cat package.json | sed -n '/"version": "*/ { s///; s/".*//; p; q; }')-${{github.run_number}}
          npm run distribute
        env:
          # We use EASY_AUTH_TOKEN because that's what's in the .npmrc
          EASY_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}